config/routes.rb
Rails.application.routes.draw do

  resources :zoos do
    resources :animals
  end

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :zoo
end

app/models/zoo.rb
class Zoo < ActiveRecord::Base
  has_many :animals

  validates :name, :location, {
    presence: true
  }

  validates :name, {
    uniqueness: true
  }
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @zoo = Zoo.find(params[:zoo_id])
  end

  def new
    @zoo = Zoo.find(params[:zoo_id])
    @animal = Animal.new
  end

  def create
    @zoo = Zoo.find(params[:zoo_id])
    new_animal = params.require(:animal).permit(:name, :photo)
    @zoo.animals.create(new_animal)
    redirect_to @zoo
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/zoos_controller.rb
class ZoosController < ApplicationController
  def index
    @all = Zoo.all
  end

  def new
    @zoo = Zoo.new
  end

  def create
    @zoo = Zoo.new(zoo_params)
    if @zoo.save
      redirect_to @zoo
    else
      redirect_to Zoo
    end
  end

  def edit
    @zoo = Zoo.find(params[:id])
  end

  def update
    @zoo = Zoo.find(params[:id])
    @zoo.update(zoo_params)
    redirect_to Zoo
  end

  def show
    @zoo = Zoo.find(params[:id])
  end

  private
  def zoo_params
    params.require(:zoo).permit(:name, :location)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zoo_helper.rb
module ZooHelper
end

app/views/animals/index.html.erb
<h1>Animals at: <%= @zoo.name %></h1>

<ul>
<% @zoo.animals.each do |animal| %>
  <li><%= animal.name %>
<% end %>
</ul>

<%= link_to "add a new animal", new_zoo_animal_path %>

app/views/animals/new.html.erb
<h1>Add new animal to <%= @zoo.name %></h1>

<%= form_for [@zoo, @animal] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :photo %>
  <%= f.text_field :photo %>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZooLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zoos/_form.html.erb
<%= form_for @zoo do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.submit "Submit" %>
<% end %>

app/views/zoos/create.html.erb
<h1>Zoo#create</h1>
<p>Find me in app/views/zoo/create.html.erb</p>

app/views/zoos/edit.html.erb
<h1>Edit Zoo</h1>

<%= render partial: "form", locals: {zoo: @zoo} %>

app/views/zoos/index.html.erb
<h1>Zoos</h1>

<ul>
<% @all.each do |zoo| %>
  <li><%= link_to zoo.name, zoo_path(zoo) %></li>
<% end %>
</ul>

app/views/zoos/new.html.erb
<h1>New Zoo</h1>

<%= render partial: "form", locals: {zoo: @zoo} %>

app/views/zoos/show.html.erb
<%= link_to "back to all zoos", zoos_path %>
<h1><%= @zoo.name %></h1>
<p><%= @zoo.location %> [<%= link_to "edit", edit_zoo_path %>]</p>

<%= link_to "see all animals", zoo_animals_path(@zoo) %>